name: fintrack

services:

  # =========================
  # Development Database
  # =========================
  postgres-dev:
    profiles: ["dev"]

    image: postgres:15

    container_name: fintrack-postgres-dev

    restart: unless-stopped

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: fintrack_db_psw
      POSTGRES_DB: fintrack_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d fintrack_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # =========================
  # Testing Database
  # =========================
  postgres-test:
    profiles: ["dev","test"]

    image: postgres:15

    container_name: fintrack-postgres-test

    restart: unless-stopped

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: fintrack_db_psw
      POSTGRES_DB: fintrack_db_test

    ports:
      - "5433:5432"

    # Ephemeral database for tests
    tmpfs:
      - /var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d fintrack_db_test"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data: