name: Python CI - Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
 check-server:
    runs-on: self-hosted
  test:
    runs-on: ubuntu-latest

    services:
      # Create a PostgreSQL service for testing purposes
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password123
          POSTGRES_DB: fintrack_db_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest
      env:
        # Env variable for test to connect to the test bd
        DATABASE_URL: postgresql://admin:password123@localhost:5432/fintrack_db_test
        DB_USER: admin
        DB_PASSWORD: password123
        DB_NAME: fintrack_db_test
      run: |
        pytest